config/routes.rb
Rails.application.routes.draw do

  root 'monsters#index'

  resources :monsters

end

app/models/monster.rb
class Monster < ActiveRecord::Base
  has_many :spottings

  def battle
    false
    # true
  end

  def weight_in_kg
    weight / 100.0
    # weight / 1000.0
  end

  def pretty_height(system: :metric)
    divisor =
      case system
      when :metric then 1000
      when :US then 304.8
      end
    (height / divisor).round(2)
    # (height / divisor).round(1)
  end

  def invisible?
    false
  end
end

app/models/spotting.rb
class Spotting < ActiveRecord::Base
  belongs_to :monster
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, except: [:new, :index, :create]

  def index
    @monsters = Monster.all
  end

  def new
    @monster = Monster.new
  end

  def create
    Monster.create(monster_params)
    redirect_to action: 'index'
  end

  def edit
  end

  def update
    @monster.update(monster_params)
    redirect_to action: 'index'
  end

  private

  def set_monster
    @monster = Monster.find(params[:id])
  end

  def monster_params
    params.require(:monster).permit(:name, :cp, :monster_type, :weight, :height)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PocketMonsters</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<h1>Pocket Monsters</h1>

<%= yield %>

</body>
</html>

app/views/monsters/_form.html.erb
<%= form_for monster do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :cp %>:
  <%= f.text_field :cp %><br />

  <%= f.label :monster_type %>:
  <%= f.text_field :monster_type %><br />

  <%= f.label :weight %>:
  <%= f.text_field :weight %><br />

  <%= f.label :height %>:
  <%= f.text_field :height %><br />

  <br />

  <%= f.submit %>
<% end %>

app/views/monsters/_monster.html.erb
<div class="row">
  <div class="row-item"><%= link_to monster.name, edit_monster_path(monster) %></div>
  <div class="row-item"><%= monster.cp %></div>
  <div class="row-item"><%= monster.monster_type %></div>
  <div class="row-item"><%= monster.weight %></div>
  <div class="row-item"><%= monster.height %></div>
  <div class="row-item"><%= %></div>
</div>

app/views/monsters/edit.html.erb
<h2>Edit Monster</h2>

<%= render 'form', monster: @monster %>

app/views/monsters/index.html.erb
<h2>Index</h2>

<p><%= link_to 'New Monster', new_monster_path %></p>

<div class="row-header row">
  <div class="row-item">Name</div>
  <div class="row-item">CP</div>
  <div class="row-item">Type</div>
  <div class="row-item">Weight</div>
  <div class="row-item">Height</div>
  <div class="row-item">Last Spotted</div>
</div>

<%= render @monsters %>

app/views/monsters/new.html.erb
<h2>New Monster</h2>

<%= render 'form', monster: @monster %>